### PR TITLE
Deploy git status

### PR DESCRIPTION
**Pull request by timmac-qmc**
Add support for checking git status before deployment

### CODE REVIEW

**Comment by SuperJMN** [comment]
Hi! I'm on mobile and can't check the changes. Can you tell me what does this PR do? Thanks!

**Comment by timmac-qmc** [comment]
Adds a setting that when true, will check the project git status. 
If there are pending changes you'll get a prompt in the console window asking if you want to proceed (y/n).

**Comment by timmac-qmc** [comment]
Have you had a chance to review?

**Comment by SuperJMN** [comment]
Hey! sorry for the delay. I think this scenario is not worth the effort. The Git status of the files doesn't have a direct relationship with a deployment to a device. I don't see why you would want to check anything related to Git to deploy an application to a device. 

It looks like a niche feature that includes another dependency that simply doesn't pay off.

**Comment by timmac-qmc** [comment]
The purpose is for team development and prevent users from deploying uncommitted changes.
I'm not sure I follow the concern about the dependency, it's not causing any harm but if you're not happy to merge I'll just spin off my own version.

**Comment by SuperJMN** [comment]
> The purpose is for team development and prevent users from deploying uncommitted changes. I'm not sure I follow the concern about the dependency, it's not causing any harm but if you're not happy to merge I'll just spin off my own version.

From the responsibility side of this library, any source control system is extraneous to it. It should no have concerns regarding to anything but deploying. For sure extra checks will be needed in specific scenarios, but its the consumer who needs to perform them. I have the impression that you want to add that functionality because it's handy. That's not enough to be included as part of this tool. You could create a work pipeline lile this:

<Some script>
- ensure no pending changes in repo
- deploy

I hope you get the idea :)

I'm closing this for the aforementioned reason. 
Thanks anyways!

**Pull request closed without merging**
